# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6993b28f82975d7a29948629818f0f0673ac6f262973de4552dcb965f70bdf2ee9bd92bb99f1077ec3526e277c4174ec07d72475ee6d880deea7df5f5f3bc73b

test:
  secret_key_base: 8210f9ec0bc4ef504316c33382281b5d1b0553fda02133404049332e97bd5f32fafc4f255a56116a6de61eb3020c2132996b02e2d447564beae88405a77093a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
